// Mocks generated by Mockito 5.4.2 from annotations
// in movie_app/test/datasource/moviedb_datasource_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:movie_app/domain/entities/movie.dart' as _i3;
import 'package:movie_app/infrastructure/datasources/moviedb_datasource.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMovie_1 extends _i1.SmartFake implements _i3.Movie {
  _FakeMovie_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MoviedbDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMoviedbDatasource extends _i1.Mock implements _i4.MoviedbDatasource {
  MockMoviedbDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set dioInitial(_i2.Dio? _dioInitial) => super.noSuchMethod(
        Invocation.setter(
          #dioInitial,
          _dioInitial,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i2.Dio);

  @override
  _i5.Future<List<_i3.Movie>> getNowPlaying({int? page = 1}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNowPlaying,
          [],
          {#page: page},
        ),
        returnValue: _i5.Future<List<_i3.Movie>>.value(<_i3.Movie>[]),
      ) as _i5.Future<List<_i3.Movie>>);

  @override
  _i5.Future<List<_i3.Movie>> getPopular({int? page = 1}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopular,
          [],
          {#page: page},
        ),
        returnValue: _i5.Future<List<_i3.Movie>>.value(<_i3.Movie>[]),
      ) as _i5.Future<List<_i3.Movie>>);

  @override
  _i5.Future<List<_i3.Movie>> getTopRated({int? page = 1}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopRated,
          [],
          {#page: page},
        ),
        returnValue: _i5.Future<List<_i3.Movie>>.value(<_i3.Movie>[]),
      ) as _i5.Future<List<_i3.Movie>>);

  @override
  _i5.Future<List<_i3.Movie>> getUpcoming({int? page = 1}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUpcoming,
          [],
          {#page: page},
        ),
        returnValue: _i5.Future<List<_i3.Movie>>.value(<_i3.Movie>[]),
      ) as _i5.Future<List<_i3.Movie>>);

  @override
  _i5.Future<_i3.Movie> getMovieById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getMovieById,
          [id],
        ),
        returnValue: _i5.Future<_i3.Movie>.value(_FakeMovie_1(
          this,
          Invocation.method(
            #getMovieById,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.Movie>);

  @override
  _i5.Future<List<_i3.Movie>> searchMovies(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchMovies,
          [query],
        ),
        returnValue: _i5.Future<List<_i3.Movie>>.value(<_i3.Movie>[]),
      ) as _i5.Future<List<_i3.Movie>>);
}
